### ISSUE TITLE
Program unusable due to initialization error related to avatar

### ISSUE THREAD

**Issue by shenghaoc** [AY1920S2-CS2103T-F09-3/main#207]
$ java -jar igrad.jar
Apr 03, 2020 1:27:42 PM igrad.MainApp init
INFO: =============================[ Initializing iGrad ]===========================
Apr 03, 2020 1:27:42 PM igrad.MainApp initConfig
INFO: Using config file : config.json
Apr 03, 2020 1:27:42 PM igrad.MainApp initPrefs
INFO: Using prefs file : C:\Users\sheng\Downloads\preferences.json
Apr 03, 2020 1:27:42 PM igrad.commons.core.LogsCenter init
INFO: currentLogLevel: INFO
Apr 03, 2020 1:27:42 PM igrad.commons.util.JsonUtil readJsonFile
INFO: Json file C:\Users\sheng\Downloads\data\coursebook.json not found
Apr 03, 2020 1:27:42 PM igrad.MainApp initModelManager
INFO: CourseBook Data file not found. Will be starting with an empty CourseBook
Apr 03, 2020 1:27:42 PM igrad.MainApp start
INFO: Starting iGrad V0.6.0ea
Apr 03, 2020 1:27:42 PM igrad.ui.UiManager start
INFO: Starting UI...
Apr 03, 2020 1:27:43 PM igrad.ui.UiManager start
SEVERE: Invalid URL: Invalid URL or resource not found
java.lang.IllegalArgumentException: Invalid URL: Invalid URL or resource not found
        at javafx.scene.image.Image.validateUrl(Image.java:1107)
        at javafx.scene.image.Image.<init>(Image.java:617)
        at igrad.ui.AvatarImage.<init>(AvatarImage.java:20)
        at igrad.ui.ResultDisplay.setAvatar(ResultDisplay.java:37)
        at igrad.ui.ResultDisplay.<init>(ResultDisplay.java:27)
        at igrad.ui.MainWindow.displayModulePanel(MainWindow.java:182)
        at igrad.ui.UiManager.start(UiManager.java:67)
        at igrad.MainApp.start(MainApp.java:183)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Invalid URL or resource not found
        at javafx.scene.image.Image.validateUrl(Image.java:1099)
        ... 16 more

Apr 03, 2020 1:27:43 PM igrad.ui.UiManager showFatalErrorDialogAndShutdown
SEVERE: Fatal error during initializing Invalid URL: Invalid URL or resource not foundInvalid URL: Invalid URL or resource not found
java.lang.IllegalArgumentException: Invalid URL: Invalid URL or resource not found
        at javafx.scene.image.Image.validateUrl(Image.java:1107)
        at javafx.scene.image.Image.<init>(Image.java:617)
        at igrad.ui.AvatarImage.<init>(AvatarImage.java:20)
        at igrad.ui.ResultDisplay.setAvatar(ResultDisplay.java:37)
        at igrad.ui.ResultDisplay.<init>(ResultDisplay.java:27)
        at igrad.ui.MainWindow.displayModulePanel(MainWindow.java:182)
        at igrad.ui.UiManager.start(UiManager.java:67)
        at igrad.MainApp.start(MainApp.java:183)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Invalid URL or resource not found
        at javafx.scene.image.Image.validateUrl(Image.java:1099)
        ... 16 more

Maybe it's because I don't have an image called sample?

    /*public static Avatar getAvatar() {
        try {
            return AvatarStorage.readAvatar();
        } catch (FileNotFoundException e) {
            return getSampleAvatar();
        }
    }*/

    public static Avatar getSampleAvatar() {
        Avatar sampleAvatar = new Avatar("sample");

        return sampleAvatar;
    }

![init_error](https://user-images.githubusercontent.com/34920365/78328472-ca2f9a80-75b1-11ea-8124-c431809652af.png)

**Comment by yjskrs** [comment]
Did you put it in an empty folder? Could you try again after deleting all the other files generated by opening the jar?

**Comment by shenghaoc** [comment]
Thanks for the fast reply, the app works now that I have created a new folder and put it in.
